export default [
  "updatePlaylist",
  "playPlaylist",
  "playSongInPlaylist",
  "addPlaylistToQueue",
  "playAlbum",
  "addAlbumToQueue",
  "playSongInAlbum",
  "playArtistSong",
  "playSongOfArtist",
  "addArtistSongToQueue",
  "playLikedSong",
  "addLikedSongToQueue",
  "addToQueue",
  "playSong",
];
